language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

install: composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover -v
  - composer update --no-interaction --prefer-source
  - vendor/bin/phpunit -v

before_script:
 - composer install --no-interaction

notifications:
  email:
    - melvyn.marigny@gmail.com
